---
inputs:
  files:
    default_value: "file:///exp2801-04-ds731218.msf"
    test_value: "file:///exp2801-04-ds731218.msf"
    label: "MSF file"
  config:
    default_value: "file:///msf.json"
    test_value: "file:///msf.json"
    label: "Configuration file (JSON)"
parameters:
outputs:
runtime:
  template: "agave-runner.sh"
  container:
    docker_org: "sd2e/"
    docker_image: "msf"
    image_tag: ":latest"
