---
inputs:
  files:
    default_value: "file:///ec_K12.fasta"
    test_value: "file:///ec_K12.fasta"
    label: "fasta or mzML file"
  config:
    default_value: "file:///lcms.json"
    test_value: "file:///lcms.json"
    label: "Configuration file (JSON)"
parameters:
outputs:
runtime:
  template: "agave-runner.sh"
  container:
    docker_org: "sd2e/"
    docker_image: "lcms"
    image_tag: ":latest"
