provider:
  name: abaco
  gateway: http://api.sd2e.org/v2/reactors

functions:
    kallisto_rnaseq:
        lang: shell
        handler: ./runner.sh
        image: sd2e/kallisto_rnaseq:0.43.0
        description: "RNAseq using Kallisto"
        stateless: false
