---
inputs:
  files:
    default: "file:///LacI-CAGop_B10_B10_P3.fcs"
    test: "file:///LacI-CAGop_B10_B10_P3.fcs"
  config:
    default: "file:///fc.json"
    test: "file:///fc.json"
    min: 1
    max: 1
parameters:
  type:
    defaultValue: "geo_mean_std"
    test_value: "geo_mean_std"
    type: "string"
  label:
    default: "Dox_0.1"
    test: "Dox_0.1"
    type: "string"
outputs:
runtime:
  template: "agave-runner.sh"
  container:
    docker_org: "sd2e/"
    docker_image: "fcs"
    image_tag: ":latest"
